server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  # 配置gateway路由 断言
  cloud:
    gateway:
      # 开启从注册中心动态创建路由功能 根据微服务名称进行路由
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_get_route
          # 匹配微服务名称
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/insert/**
        - id: payment_insert_route
          # 匹配微服务名称
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
eureka:
  instance:
    prefer-ip-address: true
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
